# Generated by Django 5.2.6 on 2025-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoberryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='hours_tajik',
            field=models.CharField(default='10:00 - 23:00 ҳар рӯз', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Chocoberry TJK', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
